import { DirectoryProvider, DirectoryUser, DirectoryFilter } from './types';

const MOCK_USERS: DirectoryUser[] = [
  {
    id: 'usr_1',
    email: 'ricardo.oliveira@voltodrive.com',
    givenName: 'Ricardo',
    familyName: 'Oliveira',
    jobTitle: 'Chief Executive Officer',
    department: 'Executivo',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 567',
    managerEmail: undefined,
    startDate: new Date('2020-01-15'),
    isAdmin: true,
    suspended: false,
  },
  {
    id: 'usr_2',
    email: 'sofia.santos@voltodrive.com',
    givenName: 'Sofia',
    familyName: 'Santos',
    jobTitle: 'Product Manager',
    department: 'Produto',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 568',
    managerEmail: 'ricardo.oliveira@voltodrive.com',
    startDate: new Date('2021-03-22'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_3',
    email: 'joao.silva@voltodrive.com',
    givenName: 'João',
    familyName: 'Silva',
    jobTitle: 'Senior Software Engineer',
    department: 'Engenharia',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 569',
    managerEmail: 'ricardo.oliveira@voltodrive.com',
    startDate: new Date('2019-07-10'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_4',
    email: 'ana.ferreira@voltodrive.com',
    givenName: 'Ana',
    familyName: 'Ferreira',
    jobTitle: 'UX/UI Designer',
    department: 'Design',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 570',
    managerEmail: 'sofia.santos@voltodrive.com',
    startDate: new Date('2022-01-05'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_5',
    email: 'pedro.costa@voltodrive.com',
    givenName: 'Pedro',
    familyName: 'Costa',
    jobTitle: 'DevOps Engineer',
    department: 'Engenharia',
    officeLocation: 'Remoto',
    phoneNumber: '+351 211 234 571',
    managerEmail: 'joao.silva@voltodrive.com',
    startDate: new Date('2021-09-15'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_6',
    email: 'marta.rocha@voltodrive.com',
    givenName: 'Marta',
    familyName: 'Rocha',
    jobTitle: 'Marketing Manager',
    department: 'Marketing',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 572',
    managerEmail: 'ricardo.oliveira@voltodrive.com',
    startDate: new Date('2020-06-01'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_7',
    email: 'luis.mendes@voltodrive.com',
    givenName: 'Luís',
    familyName: 'Mendes',
    jobTitle: 'Data Analyst',
    department: 'Analytics',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 573',
    managerEmail: 'sofia.santos@voltodrive.com',
    startDate: new Date('2022-02-10'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_8',
    email: 'clara.gomes@voltodrive.com',
    givenName: 'Clara',
    familyName: 'Gomes',
    jobTitle: 'Human Resources Lead',
    department: 'Pessoas',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 574',
    managerEmail: 'ricardo.oliveira@voltodrive.com',
    startDate: new Date('2020-11-03'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_9',
    email: 'tiago.almeida@voltodrive.com',
    givenName: 'Tiago',
    familyName: 'Almeida',
    jobTitle: 'Frontend Engineer',
    department: 'Engenharia',
    officeLocation: 'Porto',
    phoneNumber: '+351 220 100 101',
    managerEmail: 'joao.silva@voltodrive.com',
    startDate: new Date('2023-04-17'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_10',
    email: 'ines.barbosa@voltodrive.com',
    givenName: 'Inês',
    familyName: 'Barbosa',
    jobTitle: 'QA Engineer',
    department: 'Engenharia',
    officeLocation: 'Remoto',
    phoneNumber: '+351 220 100 102',
    managerEmail: 'joao.silva@voltodrive.com',
    startDate: new Date('2022-08-22'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_11',
    email: 'rui.dias@voltodrive.com',
    givenName: 'Rui',
    familyName: 'Dias',
    jobTitle: 'Sales Director',
    department: 'Comercial',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 580',
    managerEmail: 'ricardo.oliveira@voltodrive.com',
    startDate: new Date('2019-03-04'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_12',
    email: 'beatriz.lima@voltodrive.com',
    givenName: 'Beatriz',
    familyName: 'Lima',
    jobTitle: 'Account Executive',
    department: 'Comercial',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 581',
    managerEmail: 'rui.dias@voltodrive.com',
    startDate: new Date('2023-01-09'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_13',
    email: 'andre.pereira@voltodrive.com',
    givenName: 'André',
    familyName: 'Pereira',
    jobTitle: 'Customer Success Manager',
    department: 'Customer Success',
    officeLocation: 'Porto',
    phoneNumber: '+351 220 100 103',
    managerEmail: 'rui.dias@voltodrive.com',
    startDate: new Date('2022-05-30'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_14',
    email: 'mariana.cardoso@voltodrive.com',
    givenName: 'Mariana',
    familyName: 'Cardoso',
    jobTitle: 'Content Strategist',
    department: 'Marketing',
    officeLocation: 'Remoto',
    phoneNumber: '+351 211 234 582',
    managerEmail: 'marta.rocha@voltodrive.com',
    startDate: new Date('2023-07-11'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_15',
    email: 'francisco.nunes@voltodrive.com',
    givenName: 'Francisco',
    familyName: 'Nunes',
    jobTitle: 'Backend Engineer',
    department: 'Engenharia',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 583',
    managerEmail: 'joao.silva@voltodrive.com',
    startDate: new Date('2021-12-06'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_16',
    email: 'rita.fonseca@voltodrive.com',
    givenName: 'Rita',
    familyName: 'Fonseca',
    jobTitle: 'Brand Designer',
    department: 'Design',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 584',
    managerEmail: 'sofia.santos@voltodrive.com',
    startDate: new Date('2022-10-18'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_17',
    email: 'diogo.matos@voltodrive.com',
    givenName: 'Diogo',
    familyName: 'Matos',
    jobTitle: 'Financial Controller',
    department: 'Finanças',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 585',
    managerEmail: 'ricardo.oliveira@voltodrive.com',
    startDate: new Date('2020-02-25'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_18',
    email: 'helena.morais@voltodrive.com',
    givenName: 'Helena',
    familyName: 'Morais',
    jobTitle: 'People Operations',
    department: 'Pessoas',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 586',
    managerEmail: 'clara.gomes@voltodrive.com',
    startDate: new Date('2023-09-04'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_19',
    email: 'goncalo.teixeira@voltodrive.com',
    givenName: 'Gonçalo',
    familyName: 'Teixeira',
    jobTitle: 'Mobile Engineer',
    department: 'Engenharia',
    officeLocation: 'Porto',
    phoneNumber: '+351 220 100 104',
    managerEmail: 'joao.silva@voltodrive.com',
    startDate: new Date('2024-01-15'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_20',
    email: 'patricia.ramos@voltodrive.com',
    givenName: 'Patrícia',
    familyName: 'Ramos',
    jobTitle: 'Data Engineer',
    department: 'Analytics',
    officeLocation: 'Remoto',
    phoneNumber: '+351 211 234 587',
    managerEmail: 'sofia.santos@voltodrive.com',
    startDate: new Date('2023-03-20'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_21',
    email: 'bruno.melo@voltodrive.com',
    givenName: 'Bruno',
    familyName: 'Melo',
    jobTitle: 'Office Manager',
    department: 'Operações',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 588',
    managerEmail: 'clara.gomes@voltodrive.com',
    startDate: new Date('2021-06-14'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_22',
    email: 'catarina.vieira@voltodrive.com',
    givenName: 'Catarina',
    familyName: 'Vieira',
    jobTitle: 'Legal Counsel',
    department: 'Legal',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 589',
    managerEmail: 'ricardo.oliveira@voltodrive.com',
    startDate: new Date('2022-04-04'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_23',
    email: 'miguel.tavares@voltodrive.com',
    givenName: 'Miguel',
    familyName: 'Tavares',
    jobTitle: 'Solutions Architect',
    department: 'Engenharia',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 590',
    managerEmail: 'joao.silva@voltodrive.com',
    startDate: new Date('2018-11-12'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_24',
    email: 'leonor.batista@voltodrive.com',
    givenName: 'Leonor',
    familyName: 'Batista',
    jobTitle: 'Performance Marketing',
    department: 'Marketing',
    officeLocation: 'Lisboa',
    phoneNumber: '+351 211 234 591',
    managerEmail: 'marta.rocha@voltodrive.com',
    startDate: new Date('2024-02-01'),
    isAdmin: false,
    suspended: false,
  },
  {
    id: 'usr_25',
    email: 'antigo.colaborador@voltodrive.com',
    givenName: 'Antigo',
    familyName: 'Colaborador',
    jobTitle: 'Software Engineer',
    department: 'Engenharia',
    officeLocation: 'Lisboa',
    phoneNumber: undefined,
    managerEmail: 'joao.silva@voltodrive.com',
    startDate: new Date('2019-08-01'),
    isAdmin: false,
    suspended: true,
  },
];

export class MockDirectoryProvider implements DirectoryProvider {
  async listUsers(filter?: DirectoryFilter): Promise<DirectoryUser[]> {
    let users = [...MOCK_USERS];

    if (filter?.department) {
      users = users.filter(
        (u) => u.department?.toLowerCase() === filter.department?.toLowerCase()
      );
    }

    if (filter?.officeLocation) {
      users = users.filter(
        (u) => u.officeLocation?.toLowerCase() === filter.officeLocation?.toLowerCase()
      );
    }

    if (filter?.status === 'suspended') {
      users = users.filter((u) => u.suspended);
    } else if (filter?.status === 'active') {
      users = users.filter((u) => !u.suspended);
    }

    if (filter?.search) {
      const query = filter.search.toLowerCase();
      users = users.filter(
        (u) =>
          u.email.toLowerCase().includes(query) ||
          u.givenName.toLowerCase().includes(query) ||
          u.familyName.toLowerCase().includes(query) ||
          u.jobTitle?.toLowerCase().includes(query) ||
          u.department?.toLowerCase().includes(query)
      );
    }

    users.sort((a, b) =>
      `${a.givenName} ${a.familyName}`.localeCompare(`${b.givenName} ${b.familyName}`, 'pt')
    );

    return users;
  }

  async getUser(id: string): Promise<DirectoryUser | null> {
    return MOCK_USERS.find((u) => u.id === id) || null;
  }

  async syncUsers(): Promise<number> {
    return MOCK_USERS.length;
  }
}
